### PR TITLE
test developer name fix

### PR DESCRIPTION
**Pull request by FoxxMD**

### CODE REVIEW

**Comment by FoxxMD** [comment]
build

**Comment by FoxxMD** [comment]
bot, build io.github.foxxmd.multiscrobbler

**Comment by bbhtt** [comment]
you need a binary tag, see https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#provides

**Comment by FoxxMD** [comment]
> Console applications must add their **main binary name** to the provides tag:

@bbhtt there is no "main" binary. This is a node application. The command for running is not one word: `CONFIG_DIR=$XDG_CONFIG_HOME LOG_DIR=$XDG_CONFIG_HOME IS_LOCAL=true NODE_ENV=production node_modules/.bin/tsx src/backend/index.ts`

**Comment by bbhtt** [comment]
you use it in the manifest `command: multiscrobbler`, use that here

**Comment by FoxxMD** [comment]
Looks like ive got some issues to solve with actually running my app that I'll debug with local flatpak installs but good to know this solves my appstream validation issues. Thanks for the help @bbhtt

**Pull request closed without merging**
